### ISSUE TITLE
It is recommended to support multiple GPU cards

### ISSUE THREAD

**Issue by chunxiao369** [xxw1995/chatglm3-finetune#16]
Traceback (most recent call last):
  File "finetune.py", line 70, in <module>
    main()
  File "finetune.py", line 55, in main
    model = get_peft_model(model, peft_config).to("cuda")
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 22.03 GiB total capacity; 20.75 GiB already allocated; 56.88 MiB free; 21.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by xxw1995** [comment]
显卡资源不够 后续会增加deepspeed或者megatronLM的代码

**Comment by xxw1995** [comment]
> Traceback (most recent call last): File "finetune.py", line 70, in main() File "finetune.py", line 55, in main model = get_peft_model(model, peft_config).to("cuda") File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 989, in to return self._apply(convert) File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply module._apply(fn) File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply module._apply(fn) File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 641, in _apply module._apply(fn) [Previous line repeated 5 more times] File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 664, in _apply param_applied = fn(param) File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 987, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 22.03 GiB total capacity; 20.75 GiB already allocated; 56.88 MiB free; 21.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

拉取最新的代码，已支持deepspeed
