### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Wangkh777** [xxw1995/chatglm3-finetune#19]
请问博主有没有在推理时infer.py遇到过这个问题
Traceback (most recent call last):
  File "infer.py", line 48, in <module>
    out = model.generate(
  File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/peft/peft_model.py", line 1130, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/utils.py", line 1572, in generate
    return self.sample(
  File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/utils.py", line 2655, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by Wangkh777** [comment]
根据网上的解决方案，将model.generate的采样概率改成greedy search，即将do_sample参数设成false，但是这样模型的回答为空值。

**Comment by xxw1995** [comment]
> 请问博主有没有在推理时infer.py遇到过这个问题 Traceback (most recent call last): File "infer.py", line 48, in out = model.generate( File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/peft/peft_model.py", line 1130, in generate outputs = self.base_model.generate(**kwargs) File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/utils.py", line 1572, in generate return self.sample( File "/data/Wangkh/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/utils.py", line 2655, in sample next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

没遇到过哈
